import { Given, When, Then } from '@badeball/cypress-cucumber-preprocessor';
import { portfolioPage } from '../../pages/PortfolioPage';

Given('the visitor opens the QA portfolio', () => { portfolioPage.visit(); });
Then('the professional name and QA title are visible', () => { portfolioPage.heroName().should('contain', 'Matías Nahuel Murua Martínez'); portfolioPage.heroTitle().should('contain', 'Software Engineer | QA Engineer | Manual & Automation'); });
Then('the page title identifies Matías Murua', () => { cy.title().should('contain', 'Matías Murua'); });
Then('the page has no horizontal overflow', () => { portfolioPage.hasNoHorizontalOverflow(); });
When('the visitor selects View my projects', () => { portfolioPage.selectProjects(); });
Then('the case studies section is visible', () => { cy.location('hash').should('eq', '#projects'); portfolioPage.projectsSection().should('be.visible'); });
When('the visitor changes the language to Spanish', () => { portfolioPage.switchToSpanish(); });
Then('the document language is Spanish', () => { cy.get('html').should('have.attr', 'lang', 'es'); });
Then('the Spanish QA title is visible', () => { portfolioPage.heroTitle().should('contain', 'Testing Manual y Automation'); });
Then('the Spanish skills heading is visible', () => { cy.contains('h2', 'Cobertura definida por el riesgo del producto.').should('be.visible'); });
Then('four project cards are visible', () => { portfolioPage.projectCards().should('have.length', 4).and('be.visible'); });
Then('the API Testing Demo project is visible', () => { cy.contains('[data-cy="project-card"]', 'API Testing Demo').should('be.visible'); });
Then('the contact action opens the professional email address', () => { portfolioPage.contactButton().should('have.attr', 'href', 'mailto:muruamatias.96@gmail.com'); });
Then('the CV download points to a PDF file', () => { portfolioPage.cvDownload().should('have.attr', 'download').then(($link) => { cy.request($link.attr('href')).its('headers.content-type').should('include', 'application/pdf'); }); });
When('the visitor uses a mobile viewport', () => { cy.viewport(390, 844); });
Then('the professional name is visible on mobile', () => { portfolioPage.heroName().should('be.visible'); });
Then('the navigation menu can be opened', () => { portfolioPage.openMobileMenu(); cy.contains('nav a', 'About').should('be.visible'); });
Then('the mobile page has no horizontal overflow', () => { portfolioPage.hasNoHorizontalOverflow(); });